### PR TITLE
Redesign loading screen

### LINKED ISSUE #7: Nicer startup screen
We could make a beautiful loading splash instead of the current text.

### PR DESCRIPTION
**Pull request by joshua-s**
Fix #7 

In conjunction with https://github.com/airbornos/airborn-server/pull/1

### CODE REVIEW

**Comment by twiss** [comment]
I kinda wanna add a circular progress bar, a bit like this one: http://jsfiddle.net/oskar/Aapn8/. But it may be too much work & code (slowing down load time) for the duration that it is, since loading only takes half a second anyway. Maybe a simple [progress element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress) would be enough. What do you think?

**Comment by joshua-s** [comment]
I think that would be really gorgeous. Would you like me to try working on that in this pr or add it later?

**Comment by twiss** [comment]
You can do it in this one ^^ I think if you want to try a circular one it
should be doable with canvas. The linked jsfiddle is an ok example. But a
linear one could be pretty too.

Op 29 aug. 2016 19:37 schreef "Joshua Smith" <notifications@github.com>:

**Comment by joshua-s** [comment]
Circular design implemented!

**Comment by twiss** [comment]
Merged in 986adab26252830d1e3100964e0e434ce8d17858.

Thanks! :D Really cool.

**Pull request closed without merging**
